version: '2'

services:
  volume:
    build: ./volume
    image: blog_volume

  db:
    depends_on:
      - volume
    build: ./db
    image: blog_db
    mem_limit: 268435456
    volumes_from:
      - volume
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: ./wordpress
    image: blog_app
    mem_limit: 268435456
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress